name: go test

on: [push]

jobs:
  build:
    runs-on: ubicloud-standard-2-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go get .
      - run: go test
